name: pastoral_pdf_organizer
description: A new Flutter project for organizing PDFs with flexible structures and tags.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.0
  uuid: ^4.0.0
  file_picker: ^8.0.0+1
  path: ^1.9.0
  sqflite: ^2.3.3+1
  crypto: ^3.0.3
  permission_handler: ^11.3.1
  syncfusion_flutter_pdfviewer: ^26.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sqflite_common_ffi: ^2.3.3

flutter:
  uses-material-design: true
